export const FA_ICONS = {
  solid: [
    "fa-user",
    "fa-users",
    "fa-gauge",
    "fa-gear",
    "fa-bars",
    "fa-house",
    "fa-folder",
    "fa-file",
    "fa-key",
    "fa-chart-line",
    "fa-bell",
    "fa-envelope",
    "fa-lock",
    "fa-database",
    "fa-calendar",
    "fas fa-home",
    "fas fa-tools",
    "fas fa-sliders-h",
    "fas fa-cogs",
  ],
  regular: [
    "fa-user",
    "fa-folder",
    "fa-file",
    "fa-calendar",
    "fa-bell",
    "fas fa-user-times",
    "fas fa-user-shield",
    "fas fa-user-plus",
    "fas fa-user-friends",
    "fas fa-user-minus",
  ],
  brands: ["fa-vuejs", "fa-github", "fa-google", "fa-facebook", "fa-twitter"],
};
